apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: collector-cron-collect
spec:
    schedule: "*/5 * * * *"
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy: Never
                    containers:
                        -   name: collect-sankt-peterburg
                            image: mrsuh/rent-collector:1.3.1
                            envFrom:
                                -   configMapRef:
                                        name: collector-configmap-1.1.0
                                -   secretRef:
                                        name: collector-secrets-1.0.0
                            volumeMounts:
                                -   name: collector-persistent-storage
                                    mountPath: /tokenStorage
                            command: ["php"]
                            args: [
                                "bin/console", "app:collect",
                                "--city=sankt-peterburg", "--valid-period=10 minutes",
                                "--city=moskva", "--valid-period=10 minutes",
                                "--city=novosibirsk", "--valid-period=10 minutes",
                                "--city=ekaterinburg", "--valid-period=10 minutes",
                                "--city=nizhny-novgorod", "--valid-period=10 minutes",
                                "--city=kazan", "--valid-period=10 minutes",
                                "--city=chelyabinsk", "--valid-period=10 minutes",
                                "--city=omsk", "--valid-period=10 minutes",
                                "--city=samara", "--valid-period=10 minutes",
                                "--city=rostov-na-donu", "--valid-period=10 minutes",
                                "--city=ufa", "--valid-period=10 minutes",
                                "--city=krasnoyarsk", "--valid-period=10 minutes",
                                "--city=perm", "--valid-period=10 minutes",
                                "--city=voronezh", "--valid-period=10 minutes",
                                "--city=volgograd", "--valid-period=10 minutes",
                                "--city=krasnodar", "--valid-period=10 minutes",
                                "--city=saratov", "--valid-period=10 minutes",
                                "--city=tumen", "--valid-period=10 minutes",
                                "--city=togliatti", "--valid-period=10 minutes",
                                "--city=taganrog", "--valid-period=10 minutes",
                                "--city=tobolsk", "--valid-period=10 minutes",
                            ]
                    volumes:
                        -   name: collector-persistent-storage
                            persistentVolumeClaim:
                                claimName: collector-pv-claim